name: Deploy on VPS

on:
  push:
    branches: [main]         

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with rsync 
        uses: burnett01/rsync-deployments-action@v8
        with:
          switches: -avzr --delete --exclude='.git*'
          path: src/                          
          remote_path: ${{ secrets.VPS_FOLDER }}   
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_port: ${{ secrets.VPS_PORT || '22' }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}